apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: proyecto
  labels:
    app: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: crazymax/samba:latest
          env:
            - name: TZ
              value: "Europe/Madrid"
            # Samba necesita saber la contraseña del admin de LDAP para leer la base de datos
            # IMPORTANTE: Esta variable la usa el script de arranque para hacer 'smbpasswd -w'
            - name: SAMBA_LDAP_PASSWORD 
              value: "lasquepasancosas" 
          ports:
            - containerPort: 445
              name: cifs
            - containerPort: 139
              name: netbios
          volumeMounts:
            - name: config-volume
              mountPath: /etc/samba/smb.conf
              subPath: smb.conf
            - name: data-volume
              mountPath: /srv/samba/compartido
      volumes:
        - name: config-volume
          configMap:
            name: samba-config
        - name: data-volume
          emptyDir: {} # En el futuro, esto debería ser un PVC (NFS)