apiVersion: v1
kind: Service
metadata:
  name: samba-server
  namespace: proyecto
spec:
  selector:
    app: samba
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
      name: cifs
    - protocol: TCP
      port: 139
      targetPort: 139
      name: netbios