apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: proyecto
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
    - name: rpcbind
      port: 111
      targetPort: 111
    - name: mountd
      port: 20048
      targetPort: 20048
  type: ClusterIP
