apiVersion: v1
kind: ConfigMap
metadata:
  name: autofs-config
  namespace: proyecto
data:
  auto.master: |
    /home  /etc/auto.home

  auto.home: |
    *  -rw,soft,intr  nfs-server.proyecto.svc.cluster.local:/exports/home/&
