apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-seed-data
  namespace: proyecto
data:
  01-base.ldif: |
    dn: ou=usuarios,dc=inf
    objectClass: organizationalUnit
    ou: usuarios

    dn: ou=grupos,dc=inf
    objectClass: organizationalUnit
    ou: grupos

  02-pepe.ldif: |
    dn: uid=pepe,ou=usuarios,dc=inf
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: Pepe
    sn: Pruebas
    uid: pepe
    uidNumber: 2000
    gidNumber: 2000
    homeDirectory: /home/pepe
    loginShell: /bin/bash
    userPassword: password123

  03-grupos.ldif: |
    dn: cn=tecnicos,ou=grupos,dc=inf
    objectClass: posixGroup
    cn: tecnicos
    gidNumber: 2000
    memberUid: pepe
