apiVersion: v1
kind: Service
metadata:
  name: openldap-svc
  namespace: proyecto
spec:
  ports:
    - port: 389
      targetPort: 389
      name: ldap
  selector:
    app: openldap
  clusterIP: None
