apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: proyecto
  labels:
    app: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: crazymax/samba:latest
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: SAMBA_LDAP_PASSWORD
              value: "lasquepasancosas"
          ports:
            - containerPort: 445
              name: cifs
            - containerPort: 139
              name: netbios
          volumeMounts:
            - name: config-volume
              mountPath: /etc/samba/smb.conf
              subPath: smb.conf
            - name: data-volume
              mountPath: /srv/samba/compartido
              subPath: compartido
      volumes:
        - name: config-volume
          configMap:
            name: samba-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: nfs-data
